export const ROUTES = {
    LOGIN: 'LOGIN',
    ADMIN_DASHBOARD: 'ADMIN_DASHBOARD',
    ADMIN_HOME: 'ADMIN_HOME',
    ADMIN_CUSTOMERS: 'ADMIN_CUSTOMERS',
    ADMIN_PROPERTIES: 'ADMIN_PROPERTIES',
    ACCOUNT_INFO: 'ACCOUNT_INFO',
    ADD_PROPERTY_FORM: 'ADD_PROPERTY_FORM',
    PROPERTY_DETAILS: 'PROPERTY_DETAILS',
    ADD_CUSTOMER_FORM: 'ADD_CUSTOMER_FORM',
}